import { Property, MarketData } from '../types';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Modern Downtown Condo',
    address: '123 Main St, Downtown, NY 10001',
    price: 750000,
    currency: 'USD',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    yearBuilt: 2018,
    propertyType: 'condo',
    imageUrl: 'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg',
    description: 'Stunning modern condo with city views and luxury amenities.',
    isFavorite: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    features: ['City View', 'Balcony', 'Gym Access', 'Doorman'],
    neighborhood: 'Downtown',
    pricePerSqft: 625,
    listingAgent: 'Sarah Johnson',
    daysOnMarket: 15,
  },
  {
    id: '2',
    title: 'Charming Family House',
    address: '456 Oak Ave, Suburbia, NY 12345',
    price: 485000,
    currency: 'USD',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2400,
    yearBuilt: 2010,
    propertyType: 'house',
    imageUrl: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg',
    description: 'Beautiful family home with spacious yard and modern updates.',
    isFavorite: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
    features: ['Large Yard', 'Garage', 'Updated Kitchen', 'Fireplace'],
    neighborhood: 'Suburbia',
    pricePerSqft: 202,
    listingAgent: 'Mike Chen',
    daysOnMarket: 8,
  },
  {
    id: '3',
    title: 'Luxury Townhouse',
    address: '789 Park Pl, Uptown, NY 10002',
    price: 920000,
    currency: 'USD',
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 1800,
    yearBuilt: 2020,
    propertyType: 'townhouse',
    imageUrl: 'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg',
    description: 'Elegant townhouse with premium finishes and private patio.',
    isFavorite: false,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
    features: ['Private Patio', 'Hardwood Floors', 'Modern Appliances', 'Walk-in Closet'],
    neighborhood: 'Uptown',
    pricePerSqft: 511,
    listingAgent: 'Emily Rodriguez',
    daysOnMarket: 3,
  },
  {
    id: '4',
    title: 'Cozy Studio Apartment',
    address: '321 Elm St, Midtown, NY 10003',
    price: 295000,
    currency: 'USD',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 650,
    yearBuilt: 2015,
    propertyType: 'apartment',
    imageUrl: 'https://images.pexels.com/photos/2121121/pexels-photo-2121121.jpeg',
    description: 'Perfect starter home with efficient layout and great location.',
    isFavorite: true,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
    features: ['High Ceilings', 'Natural Light', 'Near Transit', 'Pet Friendly'],
    neighborhood: 'Midtown',
    pricePerSqft: 454,
    listingAgent: 'David Kim',
    daysOnMarket: 12,
  },
  {
    id: '5',
    title: 'Piso Moderno en Madrid Centro',
    address: 'Calle Gran Vía 45, Madrid, España',
    price: 450000,
    currency: 'EUR',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1100,
    yearBuilt: 2019,
    propertyType: 'apartment',
    imageUrl: 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
    description: 'Moderno apartamento en el corazón de Madrid con todas las comodidades.',
    isFavorite: false,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    features: ['Aire Acondicionado', 'Ascensor', 'Balcón', 'Cocina Equipada'],
    neighborhood: 'Centro',
    pricePerSqft: 409,
    listingAgent: 'María García',
    daysOnMarket: 7,
  },
  {
    id: '6',
    title: 'Casa Familiar en Barcelona',
    address: 'Carrer de Provença 123, Barcelona, España',
    price: 680000,
    currency: 'EUR',
    bedrooms: 4,
    bathrooms: 3,
    sqft: 1800,
    yearBuilt: 2016,
    propertyType: 'house',
    imageUrl: 'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg',
    description: 'Hermosa casa familiar con jardín privado y garaje.',
    isFavorite: true,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-11'),
    features: ['Jardín Privado', 'Garaje', 'Terraza', 'Chimenea'],
    neighborhood: 'Eixample',
    pricePerSqft: 378,
    listingAgent: 'Carlos Ruiz',
    daysOnMarket: 5,
  },
];

export const mockMarketData: MarketData = {
  averagePrice: 612500,
  priceChange: 5.2,
  totalListings: 1247,
  averageDaysOnMarket: 28,
  mostPopularType: 'house',
  trendData: [
    { date: '2024-01', price: 580000 },
    { date: '2024-02', price: 585000 },
    { date: '2024-03', price: 592000 },
    { date: '2024-04', price: 598000 },
    { date: '2024-05', price: 605000 },
    { date: '2024-06', price: 612500 },
  ],
};